export enum Altet {
  ADDEDTOFAIVERITS = "به لیست علاقه مندی ها اضافه شد",
  REMOVEDFROMFAIVERITS = "از لیست علاقه مندی ها حذف شد",
  ADDED = "در لیست علاقه مندی ها وجود دارد",
  ADDED_PRODUCT = "به سبد خرید اضافه شد",
  REMOVEPRODUCTS = "از سبد خرید حذف شد",
  SENDOTPCODE = "کد تایید به ایمیل یا شماره موبایل ارسال شد.",
  ERROROTP = "ایمیل یا شماره موبایل معتبر وارد کنید.",
  COMPARERESULT = "فقط محصولات مرتبط قابل مقایسه هستند!",
  ADDEDTOCOMPARE = "به لیست مقایسه اضافه شد",
  ALERTCOMPARE = "این محصول در لیست مقایسه وجود دارد!",
  REMOVEDCOMPARE = "از لیست مقایسه حذف شد!",
  REMOVELISTCOMPARE = "لیست مقایسه خالی شد!",
  ADDBLOGS = "بلاگ اضافه شد",
  ADDPRODUCTS = "محصول اضافه شد",
  ADDTOTRASHED = "محصول به زباله دان اضافه شد",
  BACKTOPRODUCTS = "بازگشت به محصولات",
  COMPILEDELETED = "محصول کامل حذف شد",
  SHOWPRODDUCT = "محصول قابل مشاهده است",
  NOTSHOWPRODUCT = "محصول قابل مشاهده نیست",
}
